spring.application.name=resume-reviewer-api

# Conexión MySQL XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/resumereviewdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración Spring AI con Gemini
# Configuración Gemini API Directa
# Clave real que usará nuestro RestClient para hablar con Gemini
gemini.api.key=AQ.Ab8RN6I_3sZOVfK13s6qRTXmq9HeVTMCEhn0F20lzYjdncKLvA

# Truco para satisfacer la autoconfiguración de Spring AI al arrancar
spring.ai.openai.api-key=dummy-key-para-evitar-error